blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/bug-ops/pyhdb-rs#readme
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/bug-ops/pyhdb-rs/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
